export const CREATE_TODO = 'CREATE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const SAVE_TODO = 'SAVE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const CHECK_LOGIN = 'CHECK_LOGIN'
export const LOGOUT = 'LOGOUT'
